name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      
      - name: ⭐ General
        if: ${{ success() || failure() }}
        uses: JackDevAU/metrics@latest
        with:
          filename: general.svg
          token: ${{ secrets.METRICS_GIST_TOKEN }}
          template: classic
          base: header
          config_order: base.header, isocalendar, languages, achievements
          config_timezone: Australia/Brisbane
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_ignored: tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot, vue, scala
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          plugin_languages_limit: 8
